version: 2.1

jobs:
  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.0.10
    environment:
      GOOGLE_CREDENTIALS: $GOOGLE_CREDENTIALS
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            terraform init
            terraform apply -auto-approve
